safe: false
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge

title:            The OpenTracing Project
tagline:          Consistent, expressive, vendor-neutral APIs for distributed tracing and context propagation
description:      Consistent, expressive, vendor-neutral APIs for distributed tracing and context propagation
url:              http://localhost:4000
author:
  name: The OpenTracing Authors
  url:  http://opentracing.io

collections:
  talks_and_videos:
    output: true
    permalink: /talks-and-videos/:slug

exclude:
  - node_modules
  - vendor
  - book.json
  - .gitignore
  - .nvmrc
  - book.json
  - deploy.sh
  - package.json
  - README.md