[build]
publish = "public"
command = "make build"

[context.deploy-preview]
publish = "public"
command = "make build-preview"

[context.production.environment]
HUGO_VERSION = "0.52"

[context.deploy-preview.environment]
HUGO_VERSION = "0.52"
